# Autogenerated by devscripts/update-version.py

__version__ = '2024.08.06'

RELEASE_GIT_HEAD = '90e613d244191b8f5be7a80fb8fe72751eb43d9a'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'LNTakeshi/yt-dlp'

ORIGIN = 'LNTakeshi/yt-dlp'

_pkg_version = '2024.08.06'
