# Autogenerated by devscripts/update-version.py

__version__ = '2024.08.06'

RELEASE_GIT_HEAD = '9bfb52a8694cd6bb8a207888127bedae7b755b56'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'LNTakeshi/yt-dlp'

ORIGIN = 'LNTakeshi/yt-dlp'

_pkg_version = '2024.08.06'
