# Autogenerated by devscripts/update-version.py

__version__ = '2024.05.18'

RELEASE_GIT_HEAD = '79f3632ff7a8e30ff820c16504bdcb62d63e992c'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'LNTakeshi/yt-dlp'

ORIGIN = 'LNTakeshi/yt-dlp'

_pkg_version = '2024.05.18'
